[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://cuijuolyvcocoplnfouu.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1aWp1b2x5dmNvY29wbG5mb3V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNzI3NDgsImV4cCI6MjA2NDc0ODc0OH0.k4SGu3w7Ez3bJasBGTiySJMDRgQ-CYY7aoXnmZTNWg8"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1aWp1b2x5dmNvY29wbG5mb3V1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0OTE3Mjc0OCwiZXhwIjoyMDY0NzQ4NzQ4fQ.Ew_qBqXZKjGHBxLdGCJvLYHhCvJgQKNZQNGJvLYHhCv"
  OPENAI_API_KEY = "sk-proj-VQxRzGHJKLMNOPQRSTUVWXYZ1234567890abcdefghijklmnopqrstuvwxyz"
  ELEVENLABS_API_KEY = "sk_04f6cac36cd3fb3d4a488fbc2194a6996af82a106ad79a7d"
  NEXT_PUBLIC_APP_URL = "https://graces.church"
  NODE_ENV = "production"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# API Routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Performance optimizations
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Security and Performance Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Performance Headers
    Cache-Control = "public, max-age=31536000, immutable"
    
    # CORS Headers for API
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Preload critical resources
[[headers]]
  for = "/"
  [headers.values]
    Link = "</fonts/inter.woff2>; rel=preload; as=font; type=font/woff2; crossorigin"

# Lighthouse optimizations
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

